import "./globals.css";
import { Cabin } from "next/font/google";
import { AppProvider } from "./context/appcontext";
const inter = Cabin({ subsets: ["latin"] });

export const metadata = {
  title: "Varshell | Beautifull Shoes for You",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
